on: [push]

jobs:
  custom_test:
    name: Testing a pre-condition for Omnishell (Pandora FMS)
    runs-on: ubuntu-latest

    steps:
      - name: Runs pre-condition
        uses: ks7000/pandora-fms-omnishell/action-pre-condition.yaml@master    
