# .github/workflows/test-pre-condition-action.yaml

on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Running CentOS 6 (Docker over Ubuntu) and install httpd service with rpm
    steps:
      - name: using rpm for install httpd, if necessary
        uses: ks7000/pandora-fms-omnishell@master
#        id: url
#        with:
#          url_id: https://www.ks7000.net.ve/
#      - name: Get response from curl out container
#        run: echo "curl response ${{ steps.url.outputs.http_head }}"
